image: samueldebruyn/debian-git
pipelines:
   default:
      - step:
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://185.137.235.90/garrysmod/addons/animelife